# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  initservice:
    image: initservice:1.0.2
    build:
      context: .
      dockerfile: Init-Service/Dockerfile
    ports:
      - 8072:80
